version: '2'

services:
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - webapp
    depends_on:
      - uwsgi
    container_name: nginx
  uwsgi:
    build: ./uwsgi
    volumes:
      - ./uwsgi/app.ini:/app.ini:ro
      - ./uwsgi/app.py:/app.py:ro
    networks:
      - webapp
    container_name: uwsgi
    command: uwsgi /app.ini
networks:
  webapp:
    driver: bridge
